carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path("", views.cart, name="cart"),
    path("agregar/", views.add, name="add"),
    path("eliminar/", views.remove, name="remove")
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("", views.order, name="order"),
    path("direccion/", views.address, name="address"),
    path("seleccionar/direccion/", views.select_address, name="select_address"),
    path("establecer/direccion/<int:pk>/", views.check_address, name="check_address"),
    path("confirmacion/", views.confirm, name="confirm"),
    path("cancelar/", views.cancel, name="cancel"),
    path("completar/", views.complete, name="complete"),
    path("completados/", views.OrderListView.as_view(), name="completed"),
    path("pago/", views.payment, name="payment")
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView
from products import urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", ProductListView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("usuarios/login/", views.login_view, name="login"),
    path("usuarios/logout/", views.logout_view, name="logout"),
    path("usuarios/registro/", views.register, name="register"),
    path("productos/", include("products.urls")),
    path("carrito/", include("carts.urls")),
    path("orden/", include('orders.urls')),
    path("direcciones/", include('shipping_addresses.urls')),
    path("codigos/", include("promo_code.urls")),
    path("pagos/", include("billing_profiles.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from users.models import User
from products.models import Product
from django.db.models.signals import pre_save
import uuid
from django.db.models.signals import m2m_changed, post_save
import decimal
from orders.common import OrderStatus, choices

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')    
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.05 # 0.05%

    def __str__(self):
        return self.cart_id
    
    def update_totals(self):
        self.update_subtotal()
        self.update_total()
        
        if self.order:
            self.order.update_total()

    def update_subtotal(self):
        self.subtotal = sum([cp.quantity * cp.product.price  for cp in self.products_related()])
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')
    
    @property
    def order(self):
        return self.order_set.filter(status=OrderStatus.CREATED).first()

    def has_products(self):
        return self.products.exists()

class CartProductsManager(models.Manager):
    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)
        if not created:
            quantity = object.quantity + quantity
        
        object.update_quantity(quantity=quantity)
        
        return object



class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
m2m_changed.connect(update_totals, sender=Cart.products.through)
post_save.connect(post_save_update_totals, sender=CartProducts)

carts/views.py
from django.shortcuts import render
from .models import Cart
from .utils import get_or_create_cart
from products.models import Product
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from .models import CartProducts

# Create your views here.
def cart(request):
    #Crear una sesion
    #request.session['cart_id'] = '123' # Diccionario
    #Obtenemos el valor de una sesion
    #v = request.session.get("cart_id")
    #print(v)
    # Eliminando una sesion
    #request.session['cart_id'] = None
    cart = get_or_create_cart(request)

    return render(request, "carts/cart.html", {'cart': cart})


def add(request):
    cart = get_or_create_cart(request)
    product = Product.objects.get(pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))
    
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, product=product, quantity=quantity)

    #cart.products.add(product, through_defaults={
    #    'quantity': quantity
    #})

    return render(request, "carts/add.html", {
        'product': product,
        'quantity': quantity
    })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))

    cart.products.remove(product)
    
    return redirect('carts:cart')

carts/templates/carts/add.html
{% extends "base.html" %}
{% load product_extras %}
{% load cart_extras %}

{% block content %}
    <div class="col-3">
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="imagen de producto" width="200" height="200">
        {% endif %}
    </div>
    <div class="col">
        <div class="h3 font-weight-bold text-success">
            {{ quantity | quantity_add_format }} al carrito
        </div>
        <div>
            <a href="{% url 'product' product.slug %}">{{ product.title }}</a>
        </div>
        <div class="font-weight-bold text-danger">
            {{ product.price | price_format }}
        </div>
        <div class="mt-2">
            <a href="{% url 'carts:cart' %}" class="btn btn-info">Ver carrito</a>
        </div>
        <div class="mt-2">
            <a href="{% url 'index' %}">Seguir comprando</a>
        </div>
    </div>
{% endblock content %}

carts/templates/carts/cart.html
{% extends "base.html" %}
{% load product_extras %}

{% block content %}
    {% if cart.products.exists %}
        <div class="col-8">
            <table class="table">
                <thead>
                    <tr>
                        <th col="scope"></th>
                        <th col="scope"></th>
                        <th col="scope"></th>
                        <th col="scope">Cantidad</th>
                        <th col="scope">Precio</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.products_related %}
                        {% with product=cp.product  %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <th>
                                    {% if product.image %}
                                        <img src="{{ product.image.url }}" alt="imagen del producto" width="60" height="60">
                                    {% endif %}
                                </th>
                                <th>
                                    <a href="{% url 'product' product.slug %}">{{ product.title }}</a>
                                    {% include "snippets/remove.html" %}
                                </th>
                                <th>{{ cp.quantity }}</th>
                                <th><span class="font-weight-bold text-danger">{{ product.price | price_format }}</span></th>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="font-weight-bold">
                        Subtotal({{ cart.products.count }}): <span class="text-danger">${{ cart.subtotal }}</span>
                    </div>
                    <div class="mt-2">
                        <a href="{% url 'orders:order' %}" class="btn btn-warning">Proceder al pago</a>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="col">
            <p class="h3">
                Tu carrito de compras está vacio.
            </p>
            <a href="{% url 'index' %}">Seguir comprando</a>
        </div>
    {% endif %}

{% endblock content %}