billing_profiles/urls.py
from django.urls import path
from . import views

app_name = "billing_profiles"
urlpatterns = [
    path("nuevo/", views.create, name="create"),
    path("", views.BillingProfileListView.as_view(), name="billing_profiles")
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path("", views.cart, name="cart"),
    path("agregar/", views.add, name="add"),
    path("eliminar/", views.remove, name="remove")
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView
from products import urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", ProductListView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("usuarios/login/", views.login_view, name="login"),
    path("usuarios/logout/", views.logout_view, name="logout"),
    path("usuarios/registro/", views.register, name="register"),
    path("productos/", include("products.urls")),
    path("carrito/", include("carts.urls")),
    path("orden/", include('orders.urls')),
    path("direcciones/", include('shipping_addresses.urls')),
    path("codigos/", include("promo_code.urls")),
    path("pagos/", include("billing_profiles.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/models.py
from django.db import models
from users.models import User
from stripeAPI.card import create_card


class BillingProfileManager(models.Manager):

    def create_by_stripe_token(self, user, stripe_token):
        if user.has_customer() and stripe_token:
            source = create_card(user, stripe_token)

            return self.create(card_id=source.id, 
                                last4 =source.last4,
                                token=stripe_token,
                                brand=source.brand,
                                user=user,
                                default= not user.has_billing_profiles())


class BillingProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=50, null=False, blank=False)
    card_id = models.CharField(max_length=50, null=False, blank=False)
    last4 = models.CharField(max_length=4, null=False, blank=False)
    brand = models.CharField(max_length=10, null=False, blank=False)

    default = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    objects = BillingProfileManager()

    def __str__(self):
        return self.card_id

billing_profiles/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import BillingProfile
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView

# Create your views here.


class BillingProfileListView(LoginRequiredMixin, ListView):
    login_url = "login"
    template_name ="billing_profiles/billing_profiles.html"

    def get_queryset(self):
        return self.request.user.billing_profiles


@login_required(login_url="login")
def create(request):

    if request.method == 'POST':
        if request.POST.get("stripeToken"):
            if not request.user.has_customer():
                request.user.create_customer_id()

            token = request.POST['stripeToken']
            billing_profile = BillingProfile.objects.create_by_stripe_token(request.user,token)

            if billing_profile:
                messages.success(request, "Tarjeta creada exitosamente")

    return render(request, "billing_profiles/create.html", {
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY
    })

billing_profiles/templates/billing_profiles/billing_profiles.html
{% extends "base.html" %}

{% block content %}
    <div class="col">
        <div class="h3">
            Métodos de pago
        </div>

        <div>
            <a href="{% url 'billing_profiles:create' %}">Nuevo método de pago</a>
        </div>

        <div class="mt-3">
            {% for bp in object_list %}
                {% include "billing_profiles/snippets/bp.html" %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

billing_profiles/templates/billing_profiles/create.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/stripe.css' %}">
{% endblock css %}

{% block content %}
    <div class="col">
        <div class="h3">
            Nuevo método de pago
        </div>
        <div>
            
            <form action="{% url 'billing_profiles:create' %}" method="post" id="payment-form">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-control" id="card-element" style="height: 2.4em; padding-top: 0.7em;">
                        <!-- Stripe colocará aquí los elementos -->
                    </div>
                    <div id="card-errors" role="alert">

                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Agregar nueva tarjeta</button>
            </form>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'js/stripe.js' %}"></script>
{% endblock js %}