billing_profiles/urls.py
from django.urls import path
from . import views

app_name = "billing_profiles"
urlpatterns = [
    path("nuevo/", views.create, name="create"),
    path("", views.BillingProfileListView.as_view(), name="billing_profiles")
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path("", views.cart, name="cart"),
    path("agregar/", views.add, name="add"),
    path("eliminar/", views.remove, name="remove")
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("", views.order, name="order"),
    path("direccion/", views.address, name="address"),
    path("seleccionar/direccion/", views.select_address, name="select_address"),
    path("establecer/direccion/<int:pk>/", views.check_address, name="check_address"),
    path("confirmacion/", views.confirm, name="confirm"),
    path("cancelar/", views.cancel, name="cancel"),
    path("completar/", views.complete, name="complete"),
    path("completados/", views.OrderListView.as_view(), name="completed"),
    path("pago/", views.payment, name="payment")
]

shipping_addresses/urls.py
from django.urls import path
from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path("", views.ShippingAddressListView.as_view(), name="shipping_addresses"),
    path("nuevo/", views.create, name="create"),
    path("editar/<int:pk>/", views.ShippingAddressUpdateView.as_view(), name="editar"),
    path("eliminar/<int:pk>/", views.ShippingAddressDeleteView.as_view(), name="delete"),
    path("default/<int:pk>/", views.default, name="default")
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView
from products import urls
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", ProductListView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("usuarios/login/", views.login_view, name="login"),
    path("usuarios/logout/", views.logout_view, name="logout"),
    path("usuarios/registro/", views.register, name="register"),
    path("productos/", include("products.urls")),
    path("carrito/", include("carts.urls")),
    path("orden/", include('orders.urls')),
    path("direcciones/", include('shipping_addresses.urls')),
    path("codigos/", include("promo_code.urls")),
    path("pagos/", include("billing_profiles.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online store</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% if stripe_public_key %}
        <meta name="stripe_public_key" content="{{ stripe_public_key }}">
    {% endif %}
    
    {% block css %}
    {% endblock css %}
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        {% include "messages.html" %}
        {% block breadcrumb %}
        {% endblock breadcrumb %}
        <div class="row mt-3">
            
            {% block content %}
              
            {% endblock content %}

        </div>
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://kit.fontawesome.com/ca8d149fe5.js" crossorigin="anonymous"></script>
{% block js %}
  
{% endblock js %}
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
        <div class="col">
            <h4 class="text-center">{{ message }}</h4>
            {% include "products/snippets/search.html" %}


            {% if is_paginated %}
                <div class="mt-2">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                            </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="#" class="page-link">Previous</a>
                                </li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            
                                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                </li>
                            
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                            </li>   
                        {% else %}             
                                <li class="page-item disabled">
                                    <a href="#" class="page-link">Next</a>
                                </li>   
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
            {% include "products/snippets/list.html" %}
        </div>
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'success' %}alert-info{% else %}alert-danger{% endif %}">
            <button type="button" class="close" data-dismiss="alert">x</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as sp %}
{% url 'orders:completed' as completed %}
{% url 'billing_profiles:billing_profiles' as billing_profiles %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Online store</a>
    <button type="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navb"  class="navbar-collapse collapse hide">

        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart %}active{% endif %}">
                <a href="{{ cart }}" class="nav-link">Mi carrito <span class="fas fa-shopping-cart"></span> </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item {% if request.path == sp %}active{% endif %}">
                    <a href="{{ sp }}" class="nav-link">Mis direcciones <span class="fas fa-location-arrow"></span></a>
                </li>
                
                <li class="nav-item {% if request.path == completed %}active{% endif %}">
                    <a href="{{ completed }}" class="nav-link">Mis pedidos <span class="fas fa-shipping-fast"></span></a>
                </li>
                <li class="nav-item {% if request.path == billing_profiles %}active{% endif %}">
                    <a href="{{ billing_profiles }}" class="nav-link">Mis métodos de pago <span class="fab fa-cc-stripe"></span></a>
                </li>
            {% endif %}
        </ul>

        <ul class="nav navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="fas fa-sign-in-alt"></span>
                        Logout
                    </a>
                </li>
            {% else %}

                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{ login }}" class="nav-link">
                        <span class="fas fa-user"></span>
                        Login
                    </a>
                </li>
                <li class="navbar-item {% if request.path == register %}active{% endif %}">
                    <a href="{{ register }}" class="nav-link">
                        <span class="fas fa-user-plus"></span>
                        Registro
                    </a>
                </li>


            {% endif %}
            
        </ul>
    </div>
</nav>